spring:
  application.name: transactional-outbox
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/todos
    username: todos
    password: todos
  jpa:
    hibernate:
      ddl-auto: validate
    jdbc:
      time_zone: UTC
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

app:
  outbox:
    scheduler-cron: '0 * * * * *'

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG